"""empty message

Revision ID: 029e02c8f502
Revises: 80f28b729c6f
Create Date: 2025-04-01 15:55:00.758642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029e02c8f502'
down_revision = '80f28b729c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('churn_risk')
    # ### end Alembic commands ###
