"""empty message

Revision ID: 1aa9cc01800a
Revises: d54ae5b350b6
Create Date: 2025-04-12 18:06:44.251333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa9cc01800a'
down_revision = 'd54ae5b350b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_index('ix_churn_risk_customer_id')
        batch_op.create_unique_constraint(None, ['customer_id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_complaints')
        batch_op.drop_index('ix_customers_complaints_per_transaction')
        batch_op.drop_index('ix_customers_customer_id')
        batch_op.drop_index('ix_customers_online_usage')
        batch_op.drop_index('ix_customers_transaction_volume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_transaction_volume', ['transaction_volume'], unique=False)
        batch_op.create_index('ix_customers_online_usage', ['online_usage'], unique=False)
        batch_op.create_index('ix_customers_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_customers_complaints_per_transaction', ['complaints_per_transaction'], unique=False)
        batch_op.create_index('ix_customers_complaints', ['complaints'], unique=False)

    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_churn_risk_customer_id', ['customer_id'], unique=True)

    # ### end Alembic commands ###
