"""empty message

Revision ID: 21efd5c3e9d6
Revises: cb5b343188c3
Create Date: 2025-04-05 12:47:39.798116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21efd5c3e9d6'
down_revision = 'cb5b343188c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('account_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('account_tenure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('credit_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transaction_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('online_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('complaints',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('complaints_per_transaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint('customers_customer_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint('customers_customer_id_key', ['customer_id'])
        batch_op.alter_column('complaints_per_transaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('complaints',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('online_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('transaction_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('credit_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('account_tenure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('account_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
