"""empty message

Revision ID: 54ef269b0468
Revises: c2bee3fd1bc5
Create Date: 2025-04-05 16:22:34.454734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ef269b0468'
down_revision = 'c2bee3fd1bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_tenure', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
