"""empty message

Revision ID: 76cebb2ac53c
Revises: d81c90868214
Create Date: 2025-04-01 17:53:13.272573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cebb2ac53c'
down_revision = 'd81c90868214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('account_tenure', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transaction_volume', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('online_usage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('complaints', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('complaints_per_transaction', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_column('complaints_per_transaction')
        batch_op.drop_column('complaints')
        batch_op.drop_column('online_usage')
        batch_op.drop_column('transaction_volume')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('account_balance')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
