"""empty message

Revision ID: 80f28b729c6f
Revises: 
Create Date: 2025-03-30 19:18:17.036116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f28b729c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('account_tenure', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('transaction_volume', sa.Integer(), nullable=False),
    sa.Column('online_usage', sa.Float(), nullable=False),
    sa.Column('complaints', sa.Integer(), nullable=False),
    sa.Column('complaints_per_transaction', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
