"""empty message

Revision ID: 89f594237bb7
Revises: ea6c512ffd0c
Create Date: 2025-04-05 15:30:34.479707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f594237bb7'
down_revision = 'ea6c512ffd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('online_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('complaints', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complaints_per_transaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    # ### end Alembic commands ###
