"""empty message

Revision ID: bb354f0879ce
Revises: 18dc4bb6d484
Create Date: 2025-04-05 11:23:43.978233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb354f0879ce'
down_revision = '18dc4bb6d484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('age')
        batch_op.drop_column('account_balance')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('age')
        batch_op.drop_column('account_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_tenure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_tenure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###
