"""empty message

Revision ID: cb5b343188c3
Revises: eb759d3a07bf
Create Date: 2025-04-05 12:17:01.811956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5b343188c3'
down_revision = 'eb759d3a07bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_data')
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('account_tenure', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transaction_volume', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('online_usage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('complaints', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('complaints_per_transaction', sa.Float(), nullable=False))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('account_tenure', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('credit_score')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('account_balance')
        batch_op.drop_column('age')

    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_column('complaints_per_transaction')
        batch_op.drop_column('complaints')
        batch_op.drop_column('online_usage')
        batch_op.drop_column('transaction_volume')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_tenure')
        batch_op.drop_column('account_balance')
        batch_op.drop_column('age')

    op.create_table('uploaded_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='uploaded_data_pkey'),
    sa.UniqueConstraint('customer_id', name='uploaded_data_customer_id_key')
    )
    # ### end Alembic commands ###
