"""empty message

Revision ID: d54ae5b350b6
Revises: 54ef269b0468
Create Date: 2025-04-10 18:07:19.975253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54ae5b350b6'
down_revision = '54ef269b0468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_constraint('churn_risk_customer_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_churn_risk_customer_id'), ['customer_id'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_complaints'), ['complaints'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_complaints_per_transaction'), ['complaints_per_transaction'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_online_usage'), ['online_usage'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_transaction_volume'), ['transaction_volume'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_transaction_volume'))
        batch_op.drop_index(batch_op.f('ix_customers_online_usage'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customers_complaints_per_transaction'))
        batch_op.drop_index(batch_op.f('ix_customers_complaints'))

    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_churn_risk_customer_id'))
        batch_op.create_unique_constraint('churn_risk_customer_id_key', ['customer_id'])

    # ### end Alembic commands ###
