"""empty message

Revision ID: ea6c512ffd0c
Revises: e696576f7fee
Create Date: 2025-04-05 15:10:31.256373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6c512ffd0c'
down_revision = 'e696576f7fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.alter_column('credit_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.alter_column('credit_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('online_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('complaints', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complaints_per_transaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account_tenure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    # ### end Alembic commands ###
