"""empty message

Revision ID: eb759d3a07bf
Revises: bb354f0879ce
Create Date: 2025-04-05 11:40:17.240376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb759d3a07bf'
down_revision = 'bb354f0879ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.drop_column('complaints')
        batch_op.drop_column('transaction_volume')
        batch_op.drop_column('complaints_per_transaction')
        batch_op.drop_column('online_usage')
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('extra_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('churn_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('online_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('complaints_per_transaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transaction_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('complaints', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('uploaded_data')
    # ### end Alembic commands ###
